<a href="https://colab.research.google.com/github/Karan-veer-009/40-day-ml-bootcamp/blob/main/DAY01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Examples


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
#Get Dimension
print(a.ndim)
#Get Shape
a.shape
b=np.arange(15).reshape(3,5)
print(b)
#get aspecific element[r,c]
b[2,3]
# get a row
b[1,:]
#get a column
b[:,3]
np.zeros(5)
np.ones((1,2,3))
np.full((3,2),10)
#random numbers
np.random.rand(3,2)
np.random.randint(2,8,size=(2,3))
np.identity(4)

[[1 2 3]
 [4 5 6]]
2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c=np.repeat(a,3,axis=0)
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [ ]:
#Problem 1
a=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
###### Be careful when copying arrays


In [ ]:
#Linear Algebra
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# find determinnat
c=np.full((2,2),3)
c[0:1,]=0
print(c)
print(np.linalg.det(c))

[[0 0]
 [3 3]]
0.0


In [ ]:
#Statistics
np.min(c)
np.max(c)

np.int64(3)

In [ ]:
#Reorganizinf Arrays
after=c.reshape(1,4)
print(after)

[[0 0 3 3]]


In [ ]:
#stacking
c=np.array([[1,2,3,4],[1,2,4,3]])
d=np.array([[9,8,7,6],[3,2,4,7]])
np.vstack([c,d,c])
np.hstack([c,d])

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [1, 2, 4, 3, 3, 2, 4, 7]])

In [ ]:
#np.genfromtxt('data.txt',delimiter=',')

In [ ]:
# boolean Masking and advanced indexing
d[d>5]
np.any(d>5,axis=0)
np.all(d>5,axis=0)

array([False, False, False,  True])

# Quick Exercises


In [ ]:
import numpy as np
A=np.arange(12).reshape(3,4)
print(A)
print(A[1:,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 6  7]
 [10 11]]


In [ ]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [ ]:
v=np.array([1,2,3,4])
print(A*v)#Elementwise product
A@v#matrix product

[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]


array([ 20,  60, 100])

In [ ]:
b=v.std(axis=0)
print(b)

1.118033988749895


# Practice Questions


In [ ]:
# A
import numpy as np
M=np.random.randint(-20,50,size=(500,6))
print(M)
Mean=np.mean(M,axis=0)
STD=np.std(M,axis=0)
normalize=(M-Mean)/STD
print(normalize)
z_scores =np.abs(normalize)
print((z_scores>3).sum())

[[ 40 -13  21  33 -14  43]
 [ -8  13  38  43  -4 -18]
 [-19  46  27  -7  32 -19]
 ...
 [ 31  17  45  41 -18  40]
 [  2  12  -3   4  13 -12]
 [ 35  34 -18  38  15  16]]
[[ 1.20430194 -1.30842001  0.32109091  0.83872118 -1.37310213  1.43306233]
 [-1.10150153 -0.05680411  1.15803442  1.31391732 -0.88020884 -1.64911813]
 [-1.62991483  1.53178531  0.61648274 -1.06206337  0.89420701 -1.69964568]
 ...
 [ 0.77196379  0.13575219  1.50265821  1.21887809 -1.57025945  1.28147969]
 [-0.62112581 -0.10494318 -0.86047639 -0.53934762 -0.04229024 -1.34595284]
 [ 0.96411407  0.95411643 -1.59895595  1.07631925  0.05628841  0.06881852]]
0


In [ ]:
x=np.random.rand(5_000_000)
y=np.random.rand(5_000_000)
print(x)
import time
start =time.time()
z=[a*b for a,b in zip(x.tolist(),y.tolist())]
print('list time:',time.time()-start)
start=time.time()
z_np =x*y
print("numpy time:",time.time()-start)

[0.59863285 0.92548196 0.59472073 ... 0.54514324 0.97202026 0.38199522]
list time: 0.9455955028533936
numpy time: 0.020636796951293945


These are two ways to multiple two arrays:
The one by converting into python list(loops) and other directly by numpy method(compiled), there is signficant difference between the proccessing time as seen by the result

In [ ]:
#C
a=np.random.randint(11,size=(3,3))
b=np.random.randint(11,size=(3,3))
print(np.einsum('ij,ij->',a,b))

276


# Mini Project

In [ ]:
import numpy as np
class Preprocessor:
  def __init__(self,data):
    self.data=np.array(data,dtype=float)
  def summary(self):
    return {"mean":self.data.mean(axis=0).tolist(),#Converting the mean of columns to a list with th help of tolist()
    "std":self.data.std(axis=0).tolist(),
    "min":self.data.min(axis=0).tolist(),
    "max":self.data.max(axis=0).tolist()}
  def normalize(self):
    return {"normalize":((self.data-(self.data.min(axis=0)))/(self.data.std(axis=0)+1e-8)).tolist()}
  def detect_outliers(self,z_thresh=3):
    # The 1e-8 is added to avoid being divided by zero
    z=np.abs(self.data-self.data.mean(axis=0))/(self.data.std(axis=0)+1e-8)
    return np.where(z>z_thresh)

data =np.array([
    [5,20,100],
    [9,78,2345],
    [0,98,908]
])
output=Preprocessor(data)
print(output.detect_outliers())

(array([], dtype=int64), array([], dtype=int64))


# Pandas foundations


In [1]:
import pandas as pd
#Series
s=pd.Series([1,2,3])